In [ ]:
%matplotlib inline

In [4]:
print(__doc__)

import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn import datasets

import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

Automatically created module for IPython interactive environment


ModuleNotFoundError: No module named 'sklearn'

In [3]:
ccf_train_data = "./data/2018_4_21_22_38_train.csv"
ccf_test_data = "./data/2018_4_30_08_33_test.csv"


def load_data(filepath):
    from numpy import genfromtxt

    csv_data = genfromtxt(filepath, delimiter=",", skip_header=1)
    data = []
    labels = []

    for d in csv_data:
        data.append(d[:-1])
        labels.append(d[-1])

    return np.array(data), np.array(labels)

train_dataset, train_labels = load_data(ccf_train_data)
test_dataset, test_labels = load_data(ccf_test_data)

In [98]:
predicted_lables = KMeans(n_clusters=2, init='k-means++', n_init=10, max_iter=300,).fit_predict(train_dataset)

#traning Set labels --> K Mean Clustering
predicted_lables

array([1, 1, 1, ..., 1, 1, 1])

In [99]:
missed = 0;
for i in range(0,len(predicted_lables)):
    if predicted_lables[i] != train_labels[i]:
        missed += 1

In [100]:
print("Accuracy of the K-Mean Clustering", (1 - (missed/len(y_pred)))*100)

Accuracy of the K-Mean Clustering 49.2294946147473


In [101]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [102]:
mlp = MLPClassifier(hidden_layer_sizes=(17,17,17,17,17,17,17), max_iter=500)
mlp.fit(train_dataset, predicted_lables)
    
predictions = mlp.predict(train_dataset)

In [103]:
print(classification_report(predicted_lables,predictions))

             precision    recall  f1-score   support

          0       0.97      0.99      0.98      8015
          1       0.99      0.99      0.99     16125

avg / total       0.99      0.99      0.99     24140



In [104]:
predicted_lables

array([1, 1, 1, ..., 1, 1, 1])

In [105]:
predictions

array([1, 1, 1, ..., 1, 1, 1])

In [106]:
missed = 0;
for i in range(0,len(predictions)):
    if predictions[i] != predicted_lables[i]:
        missed += 1

In [107]:
print(1 - (missed/len(predictions)))

0.9869511184755593


In [108]:
missed

315